version: '3'
services:
    namenode:
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        container_name: namenode
        restart: always
        environment:
            - CLUSTER_NAME=hadoop-cluster
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
            - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
        ports:
            - '9870:9870'
            - '9000:9000'
        volumes:
            - hadoop_namenode:/hadoop/dfs/name
            - ./data:/data
            - ./jobs:/jobs
            - ./output:/output
        networks:
            - hadoop

    datanode1:
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        container_name: datanode1
        restart: always
        environment:
            - CLUSTER_NAME=hadoop-cluster
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
            - SERVICE_PRECONDITION=namenode:9000
        volumes:
            - hadoop_datanode1:/hadoop/dfs/data
            - ./data:/data
            - ./jobs:/jobs
            - ./output:/output
        networks:
            - hadoop

    datanode2:
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        container_name: datanode2
        restart: always
        environment:
            - CLUSTER_NAME=hadoop-cluster
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
            - SERVICE_PRECONDITION=namenode:9000
        volumes:
            - hadoop_datanode2:/hadoop/dfs/data
            - ./data:/data
            - ./jobs:/jobs
            - ./output:/output
        networks:
            - hadoop

    resourcemanager:
        image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
        container_name: resourcemanager
        restart: always
        environment:
            - YARN_RESOURCEMANAGER_HOSTNAME=resourcemanager
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
            - SERVICE_PRECONDITION=namenode:9000
            - YARN_CONF_yarn_log___aggregation___enable=true
            - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
        ports:
            - '8088:8088'
        networks:
            - hadoop

    nodemanager1:
        image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
        container_name: nodemanager1
        restart: always
        environment:
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
            - SERVICE_PRECONDITION=namenode:9000 resourcemanager:8088
        networks:
            - hadoop

    historyserver:
        image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
        container_name: historyserver
        restart: always
        environment:
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
            - SERVICE_PRECONDITION=namenode:9000 resourcemanager:8088
        ports:
            - '8188:8188'
        networks:
            - hadoop

volumes:
    hadoop_namenode:
    hadoop_datanode1:
    hadoop_datanode2:

networks:
    hadoop:
